/**
 * MPU-M2 Planning Engine - LLM-Driven Planner
 *
 * Generates execution plans by delegating task decomposition to an LLM.
 * Uses Zod structured output validation to ensure generated plans are well-formed.
 *
 * Falls back to a single-step plan using the first available tool on error.
 *
 * @module
 */

import { z } from 'zod';
import type {
  Planner,
  ExecutionPlan,
  PlanStep,
  PlannerContext,
  PlanValidationResult,
  PlanValidationError,
  StepResult,
} from './types.js';
import type { LLMAdapter, LLMResponse, Message } from '../core/interfaces.js';

// ============================================================
// Zod Schemas for LLM Output Validation
// ============================================================

/**
 * Schema for a single plan step as generated by the LLM.
 * Mirrors PlanStep but without status (assigned after parsing).
 */
const llmStepSchema = z.object({
  id: z.string(),
  toolName: z.string(),
  description: z.string().optional(),
  args: z.record(z.string(), z.unknown()),
  dependsOn: z.array(z.string()).optional(),
});

const llmStepsArraySchema = z.array(llmStepSchema);

// ============================================================
// ID Generation
// ============================================================

function generatePlanId(): string {
  return `plan-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

// ============================================================
// JSON Extraction
// ============================================================

/**
 * Extract a JSON array from LLM response content.
 * Handles markdown code blocks (```json ... ``` or just ``` ... ```).
 */
function extractJsonArray(content: string): string {
  const codeBlockMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (codeBlockMatch?.[1]) {
    return codeBlockMatch[1].trim();
  }

  // Try to find a bare JSON array
  const arrayMatch = content.match(/\[[\s\S]*\]/);
  if (arrayMatch) {
    return arrayMatch[0].trim();
  }

  return content.trim();
}

// ============================================================
// LLM Planner Implementation
// ============================================================

/**
 * LLM-driven task planner.
 *
 * Delegates task decomposition to an LLM, producing structured execution plans
 * with step IDs, tool assignments, arguments, and dependency chains.
 *
 * Falls back to a keyword-free single-step plan using the first available tool
 * when the LLM call or output parsing fails.
 */
export class LLMPlanner implements Planner {
  private readonly llm: LLMAdapter;
  private readonly maxReplanAttempts: number;
  private replanAttemptCount = 0;

  /**
   * @param llm - LLM adapter for generating plans
   * @param maxReplanAttempts - Maximum replan attempts before giving up (default 2)
   */
  constructor(llm: LLMAdapter, maxReplanAttempts: number = 2) {
    this.llm = llm;
    this.maxReplanAttempts = maxReplanAttempts;
  }

  // ============================================================
  // plan() — Core plan generation
  // ============================================================

  async plan(input: string, context: PlannerContext): Promise<ExecutionPlan> {
    try {
      const prompt = this.buildPlanPrompt(input, context);
      const response = await this.callLLM(prompt);
      const steps = this.parseResponse(response, context);
      return this.buildPlan(steps);
    } catch (error) {
      console.warn(
        `[LLMPlanner] Plan generation failed, falling back to single-step plan: ${String(error)}`
      );
      return this.fallbackPlan(input, context);
    }
  }

  // ============================================================
  // validate() — Plan validation (copy PlannerImpl logic + tool names)
  // ============================================================

  // eslint-disable-next-line @typescript-eslint/require-await
  async validate(plan: ExecutionPlan, context?: PlannerContext): Promise<PlanValidationResult> {
    const errors: PlanValidationError[] = [];

    // Check: plan must have at least one step
    if (plan.steps.length === 0) {
      errors.push({
        path: 'plan',
        message: 'Plan must contain at least one step',
      });
    }

    // Check: step count must not exceed maxSteps (if context provided)
    if (context && plan.steps.length > context.maxSteps) {
      errors.push({
        path: 'plan.steps',
        message: `Plan has ${plan.steps.length} steps, exceeding maxSteps limit of ${context.maxSteps}`,
      });
    }

    // Check: step IDs must be unique
    const stepIds = new Set<string>();
    for (const step of plan.steps) {
      if (stepIds.has(step.id)) {
        errors.push({
          path: `step.${step.id}`,
          message: `Duplicate step ID: ${step.id}`,
        });
      }
      stepIds.add(step.id);
    }

    // Check: dependencies must reference existing steps
    for (const step of plan.steps) {
      if (step.dependsOn) {
        for (const depId of step.dependsOn) {
          if (!stepIds.has(depId)) {
            errors.push({
              path: `step.${step.id}.dependsOn`,
              message: `Step ${step.id} depends on non-existent step: ${depId}`,
            });
          }
        }
      }
    }

    // LLM-specific: check tool names exist in availableTools (if context provided)
    if (context) {
      for (const step of plan.steps) {
        if (!context.availableTools.includes(step.toolName)) {
          errors.push({
            path: `step.${step.id}.toolName`,
            message: `Step ${step.id} references unavailable tool: ${step.toolName}`,
          });
        }
      }
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  // ============================================================
  // replan() — Regenerate remaining steps after failure
  // ============================================================

  async replan(
    input: string,
    context: PlannerContext,
    _failedStepId: string,
    completedResults: Map<string, StepResult>
  ): Promise<ExecutionPlan> {
    this.replanAttemptCount++;
    if (this.replanAttemptCount > this.maxReplanAttempts) {
      console.warn(
        `[LLMPlanner] Replan attempt limit reached (${this.maxReplanAttempts}), returning original plan`
      );
      return this.buildCompletedOnlyPlan(completedResults);
    }

    try {
      const prompt = this.buildReplanPrompt(input, context, completedResults);
      const response = await this.callLLM(prompt);
      const newSteps = this.parseResponse(response, context);

      // Merge: keep completed steps from prior execution
      const completedStepIds = new Set(completedResults.keys());
      const mergedSteps: PlanStep[] = [];

      // Preserve completed steps with completed status
      for (const [stepId, result] of completedResults) {
        mergedSteps.push({
          id: stepId,
          toolName: '',
          args: {},
          status: result.status === 'completed' ? 'completed' : 'failed',
        });
      }

      // Filter out new steps whose IDs collide with completed steps
      for (const newStep of newSteps) {
        if (!completedStepIds.has(newStep.id)) {
          mergedSteps.push(newStep);
        }
      }

      return {
        id: generatePlanId(),
        steps: mergedSteps,
        createdAt: Date.now(),
      };
    } catch (error) {
      console.warn(`[LLMPlanner] Replan failed, returning completed steps as-is: ${String(error)}`);
      return this.buildCompletedOnlyPlan(completedResults);
    }
  }

  /**
   * Build a plan consisting only of completed steps (fallback after replan failure).
   */
  private buildCompletedOnlyPlan(completedResults: Map<string, StepResult>): ExecutionPlan {
    const steps: PlanStep[] = [];
    for (const [stepId, result] of completedResults) {
      steps.push({
        id: stepId,
        toolName: '',
        args: {},
        status: result.status === 'completed' ? 'completed' : 'failed',
      });
    }
    return {
      id: generatePlanId(),
      steps,
      createdAt: Date.now(),
    };
  }

  // ============================================================
  // Prompt Construction
  // ============================================================

  /**
   * Build the system prompt for initial plan generation.
   */
  private buildPlanPrompt(input: string, context: PlannerContext): string {
    const toolList = context.availableTools.map(t => `"${t}"`).join(', ');
    return [
      'You are a task planner. Given user input and available tools, generate an execution plan as a JSON array of steps.',
      '',
      'Each step must have:',
      '- id (unique string)',
      '- toolName (one of the available tools)',
      '- description (human-readable, optional)',
      '- args (tool arguments as object)',
      '- dependsOn (array of step IDs that must complete first; for parallel or independent steps, omit this)',
      '',
      `Available tools: [${toolList}]`,
      `Max steps: ${context.maxSteps}`,
      '',
      `User input: ${input}`,
      '',
      'Output ONLY the JSON array. No additional text.',
    ].join('\n');
  }

  /**
   * Build the system prompt for replanning after a step failure.
   */
  private buildReplanPrompt(
    input: string,
    context: PlannerContext,
    completedResults: Map<string, StepResult>
  ): string {
    const toolList = context.availableTools.map(t => `"${t}"`).join(', ');

    let completedDesc = '';
    for (const [stepId, result] of completedResults) {
      const status = result.status;
      const detail = status === 'completed' ? (result.output ?? 'ok') : (result.error ?? 'failed');
      completedDesc += `  - ${stepId}: ${status} (${detail})\n`;
    }

    return [
      'You are a task planner. A previous execution plan partially completed, but one step failed.',
      'Generate a NEW set of remaining steps to finish the task. Do NOT include steps that already completed.',
      '',
      'Already completed steps:',
      completedDesc || '  (none)',
      '',
      'Remaining task from original input:',
      `"${input}"`,
      '',
      `Available tools: [${toolList}]`,
      `Max steps: ${context.maxSteps}`,
      '',
      'Output ONLY a JSON array of remaining steps (same format as before). No additional text.',
    ].join('\n');
  }

  // ============================================================
  // LLM Invocation
  // ============================================================

  private async callLLM(prompt: string): Promise<LLMResponse> {
    const message: Message = {
      role: 'user' as const,
      content: prompt,
    };
    return this.llm.chat([message], { temperature: 0 });
  }

  // ============================================================
  // Response Parsing & Validation
  // ============================================================

  /**
   * Parse LLM response into validated PlanStep array.
   * Throws on validation failure (caught by plan()/replan() callers).
   */
  private parseResponse(response: LLMResponse, context: PlannerContext): PlanStep[] {
    const jsonText = extractJsonArray(response.content);
    let raw: unknown;

    try {
      raw = JSON.parse(jsonText);
    } catch {
      throw new Error(
        `Failed to parse LLM response as JSON. Content: ${response.content.slice(0, 200)}`
      );
    }

    // Validate structure with Zod
    const parseResult = llmStepsArraySchema.safeParse(raw);
    if (!parseResult.success) {
      throw new Error(`LLM output failed Zod validation: ${parseResult.error.message}`);
    }

    const steps: PlanStep[] = parseResult.data.map(s => {
      const step: PlanStep = {
        id: s.id,
        toolName: s.toolName,
        args: s.args,
        status: 'pending' as const,
      };
      if (s.description !== undefined) step.description = s.description;
      if (s.dependsOn !== undefined) step.dependsOn = s.dependsOn;
      return step;
    });

    // Validate tool names exist
    for (const step of steps) {
      if (!context.availableTools.includes(step.toolName)) {
        throw new Error(`Step "${step.id}" references unknown tool: ${step.toolName}`);
      }
    }

    // Validate step count
    if (steps.length > context.maxSteps) {
      throw new Error(
        `Generated ${steps.length} steps, exceeding maxSteps limit of ${context.maxSteps}`
      );
    }

    // Validate dependsOn references
    const stepIds = new Set(steps.map(s => s.id));
    for (const step of steps) {
      if (step.dependsOn) {
        for (const depId of step.dependsOn) {
          if (!stepIds.has(depId)) {
            throw new Error(`Step "${step.id}" depends on non-existent step: "${depId}"`);
          }
        }
      }
    }

    return steps;
  }

  // ============================================================
  // Plan Assembly & Fallback
  // ============================================================

  private buildPlan(steps: PlanStep[]): ExecutionPlan {
    return {
      id: generatePlanId(),
      steps,
      createdAt: Date.now(),
    };
  }

  /**
   * Fallback: create a single-step plan using the first available tool.
   * Used when LLM call or output parsing fails.
   */
  private fallbackPlan(input: string, context: PlannerContext): ExecutionPlan {
    const firstTool = context.availableTools[0];
    const steps: PlanStep[] = [];

    if (firstTool) {
      steps.push({
        id: 'fallback-step-1',
        toolName: firstTool,
        description: `Fallback: execute "${firstTool}" with raw input`,
        args: { input: input.trim() },
        status: 'pending',
      });
    }

    return {
      id: generatePlanId(),
      steps,
      createdAt: Date.now(),
    };
  }
}
